#!/bin/sh

# Update and upgrade packages
apt-get update && apt-get upgrade -y

# Install necessary repositories and Python 3.10
apt-get install -y software-properties-common
add-apt-repository ppa:deadsnakes/ppa
apt-get update
apt-get install -y python3.10 python3.10-dev python3.10-venv python3-pip libpython3.10 libpython3.10-dev

# Set default Python to 3.10
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
update-alternatives --set python3 /usr/bin/python3.10

# Install additional dependencies
apt-get install -y --no-install-recommends \
    apt-utils aria2 curl zstd git libmagic-dev \
    locales mediainfo neofetch p7zip-full \
    p7zip-rar tzdata wget qbittorrent-nox \
    autoconf automake build-essential cmake \
    g++ gcc gettext gpg-agent intltool libtool \
    make unzip zip autoconf automake libtool \
    libcurl4-openssl-dev libsodium-dev libssl-dev \
    libcrypto++-dev libc-ares-dev libsqlite3-dev \
    libfreeimage-dev swig libboost-all-dev \
    libpthread-stubs0-dev zlib1g-dev

# Create temporary directory and install FFmpeg
mkdir /Temp
cd /Temp
wget https://github.com/arakurumi/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.1-latest-linux64-nonfree-7.1.tar.xz
7z x ffmpeg-n7.1-latest-linux64-nonfree-7.1.tar.xz
7z x ffmpeg-n7.1-latest-linux64-nonfree-7.1.tar
cd /Temp/ffmpeg-n7.1-latest-linux64-nonfree-7.1/bin
mv ffmpeg /usr/bin/mediax
mv ffprobe /usr/bin/ffprobe
mv ffplay /usr/bin/ffplay
chmod +x /usr/bin/mediax /usr/bin/ffprobe /usr/bin/ffplay

# Install rclone and rename binaries
cd /Temp
curl https://rclone.org/install.sh | bash

# rename binaries
mv /usr/bin/rclone /usr/bin/remotex
mv /usr/bin/aria2c /usr/bin/fetchx
mv /usr/bin/qbittorrent-nox /usr/bin/datadlx

# Clone and build MEGA SDK
git clone https://github.com/meganz/sdk.git --depth=1 -b v4.8.0 /home/sdk
cd /home/sdk
rm -rf .git
autoupdate -fIv && ./autogen.sh
./configure --disable-silent-rules --enable-python --with-sodium --disable-examples
make -j$(nproc --all)

# Build and install the MEGA SDK Python bindings
cd bindings/python/
python3.10 setup.py bdist_wheel
pip3 install --no-cache-dir dist/megasdk-4.8.0-*.whl

# Install additional Python packages
pip3 install --no-cache-dir \
    aiofiles aiohttp aioshutil anytree apscheduler aria2p asyncio \
    cloudscraper dnspython feedparser flask gevent google-api-python-client \
    google-auth-httplib2 google-auth-oauthlib gunicorn httpx lxml motor \
    natsort pillow psutil pymongo pyrofork python-dotenv python-magic \
    qbittorrent-api requests telegraph tenacity tgcrypto urllib3 uvloop \
    xattr yt-dlp[default,curl-cffi] speedtest-cli

# Clean up unnecessary packages
apt-get remove -y \
    autoconf automake build-essential \
    cmake g++ gcc gettext gpg-agent \
    intltool libtool make unzip zip \
    libtool libcurl4-openssl-dev libssl-dev \
    libc-ares-dev libsqlite3-dev swig \
    libboost-all-dev libpthread-stubs0-dev zlib1g-dev

apt-get autoremove -y
apt-get autoclean -y

# Clean up temporary directories and files
rm -rf /Temp
rm -rf Aeon
rm -rf Dockerfile
