#!/bin/bash

# Update system (No apt-get, use apk)
update_system() {
    apk update && apk upgrade
}

# Install Python 3.12 and dependencies
install_python() {
    apk add --no-cache python3 py3-pip python3-dev
    pip install --upgrade pip
}

# Install additional system dependencies
install_dependencies() {
    apk add --no-cache \
        aria2 curl git libmagic-dev locales mediainfo neofetch \
        p7zip tzdata wget autoconf automake build-base cmake \
        gettext gpgme intltool libtool make unzip zip \
        openssl-dev libc-dev zlib-dev boost-dev
}

# Download and install qbittorrent-nox
install_qbittorrent() {
    ARCH=$(uname -m)
    mkdir -p /usr/local/bin

    case "$ARCH" in
        x86_64)
            wget -qO /usr/local/bin/xnox https://github.com/userdocs/qbittorrent-nox-static/releases/latest/download/x86_64-qbittorrent-nox
            ;;
        aarch64)
            wget -qO /usr/local/bin/xnox https://github.com/userdocs/qbittorrent-nox-static/releases/latest/download/aarch64-qbittorrent-nox
            ;;
        *)
            echo "Unsupported architecture for qbittorrent-nox: $ARCH"
            exit 1
            ;;
    esac

    chmod +x /usr/local/bin/xnox
}

# Install FFmpeg
install_ffmpeg() {
    ARCH=$(uname -m)
    mkdir -p /Temp
    cd /Temp

    case "$ARCH" in
        x86_64)
            wget https://github.com/5hojib/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.1-latest-linux64-gpl-7.1.tar.xz
            ;;
        aarch64)
            wget https://github.com/5hojib/FFmpeg-Builds/releases/latest/download/ffmpeg-n7.1-latest-linuxarm64-gpl-7.1.tar.xz
            ;;
        *)
            echo "Unsupported architecture for FFmpeg: $ARCH"
            exit 1
            ;;
    esac

    tar -xJf ffmpeg-n7.1-latest-linux*-gpl-7.1.tar.xz
    tar -xf ffmpeg-n7.1-latest-linux*-gpl-7.1.tar
    mv ./ffmpeg-n7.1-latest-linux*/bin/* /usr/bin/
    chmod +x /usr/bin/*
}

# Install rclone and rename binaries
install_rclone() {
    curl https://rclone.org/install.sh | bash
    mv /usr/bin/rclone /usr/bin/xone
    mv /usr/bin/aria2c /usr/bin/xria
}

# Install Python packages
install_python_packages() {
    pip install --no-cache-dir -U setuptools uv

    pip install --no-cache-dir \
        aiofiles aioshutil anytree apscheduler aria2p asyncio \
        cloudscraper dnspython feedparser flask gevent \
        google-api-python-client google-auth-httplib2 google-auth-oauthlib \
        gunicorn httpx lxml motor natsort pillow psutil \
        pymongo python-dotenv python-magic qbittorrent-api requests \
        telegraph tenacity urllib3 uvloop xattr yt-dlp[default,curl-cffi] \
        tgcrypto pyrofork
}

# Clone and build MEGA SDK
build_mega_sdk() {
    git clone https://github.com/meganz/sdk.git --depth=1 -b v4.8.0 /home/sdk
    cd /home/sdk
    rm -rf .git
    ./autogen.sh
    ./configure --disable-silent-rules --enable-python --with-sodium --disable-examples
    make -j$(nproc)

    cd bindings/python/
    python3 setup.py bdist_wheel
    pip install --no-cache-dir dist/megasdk-4.8.0-*.whl
}

# Clean up
cleanup() {
    rm -rf /Temp Aeon Dockerfile
}

# Main script
main() {
    update_system
    install_python
    install_dependencies
    install_qbittorrent
    install_ffmpeg
    install_rclone
    install_python_packages
    build_mega_sdk
    cleanup
}

main
